services:
  market-db:
    image: postgres:15
    container_name: market-db
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - market-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  marketplace:
    build:
      context: ./marketplace
      dockerfile: Dockerfile
    container_name: marketplace
    depends_on:
      - market-db
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MARKET_DB_URL: jdbc:postgresql://market-db:5432/market_db
      MARKET_DB_USERNAME: postgres
      MARKET_DB_PASSWORD: P@ssw0rd
      JWT_SECRET: "aB3dE5fG7hJ9kL1nP2rT4vW6xY8zA0cC2eE4gG6iI8kK0mM"
      JWT_EXPIRATION: 86400000
      ADMIN_USERNAME: "ADMIN"
      ADMIN_PASSWORD: "ADMIN"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - app-network

  notification-db:
    image: postgres:15
    container_name: notification-db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5433:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: notification
    depends_on:
      - notification-db
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      NOTIFICATION_DB_URL: jdbc:postgresql://notification-db:5432/notification_db
      NOTIFICATION_DB_USERNAME: postgres
      NOTIFICATION_DB_PASSWORD: P@ssw0rd
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.7.8
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: "notification-topic:1:1,order-events:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - app-network




volumes:
  market-db-data:
  notification-db-data:

networks:
  app-network:
    driver: bridge