package com.skinmarket.marketplace.exception;

public enum ErrorCode {
    UNEXPECTED_ERROR,
    SKIN_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    SKIN_NOT_FOUND,
    USER_NOT_FOUND,
    MARKET_ITEM_NOT_FOUND,
    MARKET_ITEM_NOT_ACTIVE,
    OPTIMISTIC_LOCK_FAILURE,
    NOT_ENOUGH_MONEY,
    VALIDATION_ERROR,
    CANNOT_BUY_OWN_ITEM
}
