spring:
  datasource:
    url: ${MARKET_DB_URL}
    username: ${MARKET_DB_USERNAME}
    password: ${MARKET_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}